Repository nu50218/impls, pull requests merged in 2020-09, with the labels that each got.

#6 impls: add UnderlyingInterface
  impls/impls.go
Labels: enhancement

#10 types: errorに対応
  command/types/types.go
Labels: bug

#14 types: exportedオプションを追加
  command/types/types.go
Labels: enhancement

#16 types: *types.TypeNameかどうかをチェック
  command/types/types.go
Labels: bug

#17 feature: サブコマンドvarsを実装する
  command/vars/vars.go
  main.go
Labels: enhancement

#18 interfaces サブコマンドを作成
  command/iface/interface.go
  command/types/types.go
  command/vars/vars.go
  impls/impls.go
  main.go
Labels: enhancement

#30 サブコマンドの第一引数のパッケージは出力に含まないようにする
  command/iface/interface.go
  command/types/types.go
  command/vars/vars.go
  impls/impls.go
Labels: bug

#33 2回同じインターフェースが表示されることを修正
  command/iface/interface.go
  command/types/types.go
  command/vars/vars.go
Labels: bug

#40 impls interfaces の表示がおかしい
  command/iface/interface.go
Labels: bug, bump:patch
